<script
    class="amocrm_oauth"
    charset="utf-8"
    data-client-id="xxxx"
    data-title="Button"
    data-compact="false"
    data-class-name="className"
    data-color="default"
    data-state="state"
    data-error-callback="functionName"
    data-mode="popup"
    src="https://www.amocrm.ru/auth/button.min.js"
></script>